library(readr)
dataset <- read_csv(NULL)
View(dataset)
names(dataset)
install.packages(ggplot2)
library(ggplot2)
q1 <- qplot(ahs_wom_odisha_gajapati$surviving_female, data = ahs_wom_odisha_gajapati,xlab = 'total_surviving_female',ylab = 'birth_count',ylim = c(0,8000))
q2 <- qplot(ahs_wom_odisha_gajapati$born_alive_female, data = ahs_wom_odisha_gajapati,xlab = 'born_alive_female',ylab = 'total_births',ylim = c(0,8000))
install.packages("gridExtra")
library(gridExtra)
grid.arrange(q1,q2,ncol = 2)