age <- rep(c("6-10 years","11-14 years","15-17 years"),2)
male<- c(96,92,69)
female<- c(95,91,62)
values <- c(male,female)
type <-c(rep("male", 3), rep("female", 3))
mydata <-data.frame(age, values)
library(ggplot2)
p <-ggplot(mydata, aes(age, values))
p +geom_bar(stat = "identity")
mydata$age <- factor(mydata$age,levels = c("6-10 years","11-14 years","15-17 years"))
p <-ggplot(mydata, aes(age, values))
p +geom_bar(stat = "identity")
p <-ggplot(mydata, aes(age, values))
p +geom_bar(stat = "identity",aes(fill = type), position = "dodge") +
  xlab("Age")+ylab("Percentage")+ggtitle("School attendance among children")+theme_bw()